### PR TITLE
couple of fixes 

### PR DESCRIPTION
**Pull request by husayt**
this fixes issue with return value for cancelling orders
also refactors request method
and adds a check if fetch is globally available, to use that

### CODE REVIEW

**Comment by 117** [comment]
`.closePosition()` is supposed to be returning an `Order` no?

**Comment by husayt** [comment]
oops.. I misread the documentation. 1 min. will fix that

**Comment by husayt** [comment]
Fix is in place. Thanks for pointing it out

**Comment by 117** [comment]
Gonna do some testing then push to NPM, great PR!

**Pull request merged**
