### PR TITLE
Support fractional shares for placeOrder

### PR DESCRIPTION
**Pull request by kevindra**
Alpaca just released fraction shares support in their API!! Updating the library to support that feature. Let me know if I missed something. :)

### CODE REVIEW

**Comment by 117** [comment]
From what I can tell `notional` should be optional along with `qty` now since they both cannot exist together. Could you make this change?

**Comment by kevindra** [comment]
Ah okay. Yes let me make that change quickly.

**Comment by kevindra** [comment]
Done!

**Comment by 117** [comment]
Version `5.1.4-beta` has your change included. Thanks for the PR!

**Comment by husayt** [comment]
This is cool. Thanks. Here is more info on the subject 
https://alpaca.markets/blog/fractional-trading/

**Pull request merged**
