### PR TITLE
added multiple bundles output via rollup and fix for commonjs

### PR DESCRIPTION
**Pull request by husayt**
I did go bit wild here. Added bundling via rollup and fix for commonjs. Let's review, please.

### CODE REVIEW

**Comment by husayt** [comment]
Also replaces events with much faster eventemitter3.

**Comment by 117** [comment]
Reviewing.

**Comment by 117** [comment]
Getting `Error: Cannot find module './client'`. Because `require("./client")` does not have the file extension `.cjs`. The obvious fix is to just go back to adding the trailing extensions then remapping them. But is there a better way?

**Comment by husayt** [comment]
It was kind of 3am, but I wanted to share it even if it was bit raw, so we could discuss it.
The problem for me I don't have cjs code to test it. Do you mind sharing something even if simple just to see that error. 
All the unit tests pass, that means we need to add more tests to cover cjs and flag that error. 

 Along with cjs and mjs, will be good to have a browser bundle (preferably umd as well as esm) , that is why I did add few more bundle options so we could review them and leave what makes most sense.

I will try to add some more examples. Just to show multiple options of using this lib.

**Comment by husayt** [comment]
> Getting `Error: Cannot find module './client'`. Because `require("./client")` does not have the file extension `.cjs`. The obvious fix is to just go back to adding the trailing extensions then remapping them. But is there a better way?

Do we really need `cjs` extension. Generally, if it is not `mjs`, then it's `cjs`. If we just leave commonjs code with js extension, then it will work ok. This is the simplest thing to do here

**Comment by husayt** [comment]
@117 Have a try now, pls

**Comment by 117** [comment]
Trying.

**Comment by 117** [comment]
Still can't get it to import via require, same error.

**Comment by husayt** [comment]
Is there a sample, where I could test it? I am using this lib from multiple places and all works fine for me.

**Comment by 117** [comment]
I am just doing `node index.js` on the example after installing `npm i husayt/alpaca`.

**Comment by husayt** [comment]
I have found the problem. Will try to get the solution which allows for node and browser, esm and commonjs consumption

**Comment by husayt** [comment]
@117 with further tweaking and replacing ky-universal with node-fetch, I got both commonjs and ESM working. 

But then, the reason ky-universal and others are stopping commonjs support, that with node 14 properly supporting ES modules, there is no much point for CJS moving forward. So maybe, we should make the switch too? Unless, we want to support legacy node, there is no need for CJS anymore. We can just produce two outputs, one for ESM modules and the other with all the dependencies bunlded for browsers. I have already spent two days on this and could get it all done and polished, so we don't need to come back to this anytime soon. And we will release next version with new major to not to break others who still want to use commonjs. The rest will just use new version. What do you think?

**Comment by 117** [comment]
First of all thank you so much for the contributions you have been making! I have been very busy with work and I appreciate you taking the time to improve the library. 🙂 

I am all for ditching commonjs support, it has gone the way of dinosaurs and I don't enjoy maintaining it. This does mean we have to push a major version change though.

**Comment by husayt** [comment]
@117 I have finally got the working configuration. Here I have set main ver to 4.0.0. As we have discussed we are not supporting commonjs going forward. That makes our lives much easier. Instead we have whole set of bundles for different use cases. 
As a cherry on the cake, I added a [microtader demo app](./examples/microtader.html) which shows how to list and order directly from browser.

There are few changes and updates which I mention below. Hope it all works fine:

To help with tree-shaking there is no default export and import is as following:

import { AlpacaClient, AlpacaStream } from '@master-chief/alpaca'

## Use directly from browser


In a browser:

```html
<script src="alpaca.browser.min.js"></script>
```
Also modern browsers allow 
```html
<script type="module">
import quranMeta from "alpaca.esm.min.js"
</script>
```

The library is available from various CDNs
* [JSDelivr](https://cdn.jsdelivr.net/npm/@master-chief/alpaca/) 
* [UnPKG](https://unpkg.com/browse/@master-chief/alpaca/)


 See provided [microtader demo app](./examples/microtader.html) and [simple classic](./examples/classic.html) examples on how to user

### Distributions and Downloads

Here you can find the following

|  |  |
|---|---|
| [Source code](https://github.com/117/alpaca/tree/main/src) in typescript | TS |
| [Javascript code](https://github.com/117/alpaca/tree/main/dist/mjs) autotranspiled from TS as ES Next | ES |
| [ESM Bundle](https://github.com/117/alpaca/blob/main/dist/alpaca.js) | ES bundled in one file |
|  |  |
|  **[distributions bundled with dependencies](https://github.com/117/alpaca/tree/main/dist) of library as** |  |
| [UMD](https://github.com/117/alpaca/blob/main/dist/alpaca.browser.js)/ [UMD minified](https://github.com/117/alpaca/blob/main/dist//alpaca.browser.min.js) builds can be used directly in the browser via a `<script>` (see  [here](https://www.syntaxsuccess.com/viewarticle/iife-vs-umd) about UMD format) | ES+UMD (for classic import user) |
|  |  |
| [ESM Browser](https://github.com/117/alpaca/blob/main/dist/alpaca.esm.js) /[ESM Browser minified](https://github.com/117/alpaca/blob/main/dist/alpaca.esm.min.js) | ES5+ESM (for modern import type="module") |
|  |  |

**Comment by husayt** [comment]
@117 thanks for reviewing and polishing. You did also mention deno compatibility. I didn't have a chance to test it, but if you manage to try it should work. Will be good to know

**Comment by 117** [comment]
@husayt So i've gotten it to work with deno! 

```typescript
import { AlpacaClient } from 'https://cdn.skypack.dev/@master-chief/alpaca'
```

Using the SkyPack CDN, Deno has no problem finding the types.

**Comment by husayt** [comment]
Great, will be very useful to mention that in readme too.

**Pull request merged**
